# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Baemin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Baemin
  pod 'SnapKit', '~> 5.0.0'
  pod 'Moya', '~> 14.0'

  target 'BaeminTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaeminUITests' do
    # Pods for testing
  end

end
